blog/urls.py
from rest_framework.routers import DefaultRouter

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('core.api.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/api/urls.py
from django.urls import path, include
from .views import (
    CommentCreateView,
    CommentDetailView,
    CommentListView,
    CommentUpdateView,
    CommentDeleteView,
)

urlpatterns = [
    path('comments/', CommentListView.as_view(), name='comment-list'),
    path('comments/create/', CommentCreateView.as_view(), name='comment-create'),
    path('comments/<int:pk>/detail/',
         CommentDetailView.as_view(), name='comment-detail'),
    path('comments/<int:pk>/update/',
         CommentUpdateView.as_view(), name='comment-update'),
    path('comments/<int:pk>/delete/',
         CommentDeleteView.as_view(), name='comment-delete'),
]

core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
urlpatterns = [
    path('', views.indexPage, name='index'),
    path('post/<str:slug>/', views.postDetail, name='post-detail'),
    # path('register/', views.registerPage, name='register'),
    # path('login/', views.loginPage, name='login'),
    path('accounts/confirm/logout/', views.logoutConfirm, name='account_confirm'),
    path('accounts/logout/', views.logoutPage, name='account_logout'),
    path('accounts/signup/', views.signupPage, name='account_signup'),
    path('profile/<str:user>/', views.profilePage, name='profile'),
    path('settings/', views.profileEditPage, name='profile-edit'),
    path('add-post/', views.addPost, name='add-post'),
    path('edit-post/<str:slug>/', views.editPost, name='edit-post'),
    path('delete-post/<str:slug>/', views.deletePost, name='delete-post'),
    path('like/<str:slug>/', views.likePost, name='like-post'),
    path('readinglist/', views.readingListPost, name='reading-list'),
    path('tagged/<str:slug>/', views.tagged, name='tagged'),
    path('readingList/<str:slug>/', views.readingListAdd, name='reading-add'),
    path('search/', views.searchPost, name='post-search'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/<str:category>/', views.dashboardData, name='dashboard-data'),
    path('following/<str:user>/', views.following, name='following'),
    path('followers/<str:user>/', views.followers, name='followers'),
    path('follow/<str:user>/', views.followAdd, name='follow'),
    path('dashboard/delete/<str:data>/',
         views.dashboardDeleteCommentPost, name='dash-delete,'),
    # since we are not using any form to upload those images we cannot set csrf token thus we need to csrf_exempt them here and we are using requires csrf token property in views
    path('fileUPload/', csrf_exempt(views.upload_file_view)),
    path('imageUPload/', csrf_exempt(views.upload_image_view)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image
from django.utils.text import slugify
from django_editorjs import EditorJsField
from allauth import socialaccount
from taggit.managers import TaggableManager
# socialaccount.providers.google.provider.OAuth2Provider.extract_extra_data
# Create your models here.


# class PersonManager(models.Manager):
#     def get_by_natural_key(self, title):
#         return self.get(title=title)
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250, blank=True)
    body = EditorJsField(editorjs_config={
        "tools": {
            "config": {
                "placeholder": 'Write your post content here...'
            },
            "Image": {
                "config": {
                    "endpoints": {
                        "byFile": '/imageUPload/',
                        "byUrl": '/imageUPload/'
                    },
                    "additionalRequestHeaders": [{"Content-Type": 'multipart/form-data'}]
                }
            },
            "Attaches": {
                "config": {
                    "endpoint": '/fileUPload/',
                },
            },
        }
    }, blank=True)
    slug = models.SlugField()
    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField()
    header = models.ImageField(upload_to='uploads', blank=True)
    snippet = models.CharField(max_length=250, blank=True)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)
    draft = models.BooleanField(default=False)
    tags = TaggableManager(blank=True)
    # objects = PersonManager()

    def natural_key(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = timezone.now()
            self.slug = slugify(self.title)
        self.modified = timezone.now()

        # img = Image.open(self.header.path)
        # if img.height > 300 or img.width > 300:
        #     output_size = (300, 300)
        #     img.thumbnail(output_size)
        #     img.save(self.image.path)

        return super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', args=[self.slug])

    class Meta:
        ordering = ['-created']
        unique_together = ['title']


class ReadingList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ManyToManyField(Post, related_name="post_read")

    def __str__(self):
        return f'{self.user} reading list'


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE,  related_name='profile_img')
    profile = models.ImageField('Profile_image',
                                default='default.jpg', upload_to='profile')
    bio = models.CharField(max_length=50, blank=True)
    location = models.CharField(max_length=250, blank=True)
    following = models.ManyToManyField(
        User, related_name='profile_following', blank=True)
    follower = models.ManyToManyField(
        User, related_name='profile_follower', blank=True)

    def __str__(self):
        return f'{self.user.username} profile'

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.profile.path)
        if img.height > 96 or img.width > 96:
            output_size = (96, 96)
            img.thumbnail(output_size)
            img.save(self.profile.path)


class Comment(models.Model):
    comment = models.CharField(max_length=500)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comment_post")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="comment_user")
    created = models.DateTimeField()

    # def save(self, *args, **kwargs):
    #     super().save()
    #     if not self.id:
    #         self.created = timezone.now()
    #     self.created = timezone.now()

    def __str__(self):
        return f'{self.user.username} comment'

core/forms.py
from django.contrib.auth.models import User
from .models import Profile, Post
from django.contrib.auth.forms import UserCreationForm
from django import forms


class PostCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'created-post-title',
            'placeholder': 'New post title here...',
            'autocomplete': 'off',
        })

        self.fields['header'].widget.attrs.update({
            'class': 'created-post-header',
            'style': 'display: none',
            'id': 'file',

        })
        self.fields['snippet'].widget.attrs.update({
            'class': 'created-post-snippet',
            'placeholder': 'Post Snippet here...',
            'autocomplete': 'off',
        })

        self.fields['body'].widget.attrs.update({
            'class': 'created-post-body',
        })

        self.fields['tags'].widget.attrs.update({
            'class': 'created-post-tags',
        })

        self.fields['draft'].widget.attrs.update({
            'class': 'created-post-draft',
            'id': 'draft'
        })

    class Meta:
        model = Post
        fields = ['header', 'title', 'tags', 'snippet', 'body', 'draft']


class UserRegisterPage(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfilePageForm(forms.ModelForm):
    profile = forms.ImageField(
        label='', widget=forms.FileInput, required=False)

    class Meta:
        model = Profile
        fields = ['profile']

core/api/views.py
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    CreateAPIView,
    UpdateAPIView,
    RetrieveDestroyAPIView,
    RetrieveUpdateAPIView
)
from core.models import Comment, Profile, Post
from .serializers import CommentSerializer
from .permissions import IsOwnerOrReadOnly
from django.utils import timezone

from rest_framework.permissions import IsAuthenticatedOrReadOnly


class CommentCreateView(CreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):
        # print('curr_post:!!!', serializer.data['id'])
        # print('SERIALIZER DATA!!!!', serializer)
        if self.request.method == "POST":
            curr_post = self.request.data['id']
            p = Post.objects.get(pk=curr_post)
            print("CHHHHHHHHHHHHHHHHECK!", p)
        # p = Post.objects.get(pk=self.request.POST.get('id'))
        serializer.save(user=self.request.user, created=timezone.now(), post=p)


class CommentListView(ListAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]


class CommentDetailView(RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]


class CommentUpdateView(RetrieveUpdateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    # def perform_create(self, serializer):
    #     # print('curr_post:!!!', serializer.data['id'])
    #     # print('SERIALIZER DATA!!!!', serializer)
    #     if self.request.method == "PUT":
    #         curr_post = self.request.data['id']
    #         p = Post.objects.get(pk=curr_post)
    #         print("CHHHHHHHHHHHHHHHHECK!", p)
    #     # p = Post.objects.get(pk=self.request.POST.get('id'))
    #     serializer.save(user=self.request.user, created=timezone.now(), post=p)


class CommentDeleteView(RetrieveDestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

core/templates/core/add_post.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
.<div class="container mb-5 ">

    <div class="container p-size">
        <form  action="" method="POST" enctype="multipart/form-data">
            <div class="p-bg mb-3">
                {% csrf_token %}
                {{ forms.media }}
                <p class="file-upload">
                    <label for="file" class="file-btn">Add cover image</label> 
                    {{forms.header}}
                </p>
                {{forms.title|as_crispy_field }}
                <div class="form-group">
                    <div>
                        <input type="text" data-role="tagsinput"  name="tags" class="form-control created-post-tags" placeholder="Add up to 4 tags...">
                    </div>
                </div>
                {{forms.snippet|as_crispy_field }}
                <p class="p-b">Write your content post below: </p>
                {{forms.body|as_crispy_field }}
            </div>
                <input type="submit" class="custom-nav create post-add "value="Post Blog">
                {{forms.draft}}
                <label for="draft">Save to draft</label>
            </form>
            
    </div>
</div>
{% endblock content %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://cdn.lineicons.com/2.0/LineIcons.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <title>Blog | Django</title>
</head>
<body>
    {% include 'core/navigation.html' %}
    {% block content %}
    {% endblock content %}
    <footer class="footer">
        <h2>Blog</h2>
      </footer>
</body>


    <script src="{% static  'js/script.js' %}" ></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</html>

core/templates/core/dashboard.html
{% extends 'core/base.html' %} {% block content %}
<div class="container min-h pt-4">
    <h1>Dashboard</h1>
    <div class="dashboard-main row row-cols-2  row-cols-md-4">
        <div class="col mb-3">
            <div class="post-list-container b-shadow">
                <div>
                    <span class="main-following-count">{{ following_count }}</span>
                    <span>Following</span>
                </div>
            </div>
        </div>
        <div class="col mb-3">
            <div class="post-list-container b-shadow">
                <div>
                    <span>{{ followers_count }}</span>
                    <span>Followers</span>
                </div>
            </div>
        </div>
        <div class="col mb-3">
            <div class="post-list-container b-shadow">
                <div>
                    <span>{{ posts.count }}</span>    
                    <span>Posts</span>
                </div>  
            </div>
        </div>

        <div class="col mb-3">
            <div class="post-list-container b-shadow">
                <div>
                    <span>{{ draft_count }}</span>    
                    <span class="text-nowrap">Draft</span>
                </div>  
            </div>
        </div>
    </div>


    <div class="dashboard-container">
        <div class="dashboard-category">
            <div class="category-container">
                <ul class="parent-list">
                    <a class="category-btn children-list selected-toggle" href="{% url 'dashboard-data' 'Post' %}">
                    <li class="">
                            Post
                        </li>
                        
                        <span class="data-count" >{% if posts %}{{ posts.count }}{% else %} 0 {% endif %}</span>
                    </a>
                    <a class="category-btn children-list" href="{% url 'dashboard-data' 'Draft' %}">
                    <li class="children-list">
                            Draft
                        </li>
                        <span class="data-count" >{{draft_count}}</span>
                    </a>
                    <a class="category-btn children-list" href="{% url 'dashboard-data' 'Following' %}">
                    <li class="children-list">
                            Following
                        </li>
                        <span class="data-count following-count" >{{ following_count }}</span>
                    </a>
                    <a class="category-btn children-list" href="{% url 'dashboard-data' 'Followers' %}">
                    <li class="children-list">
                            Followers
                        </li>
                        <span class="data-count" >{{ followers_count }}</span>
                        </a>
                        <a class="category-btn children-list" href="{% url 'dashboard-data' 'Comment' %}">
                            <li class="children-list">
                                    Comments
                                </li>
                                <span class="data-count" >{{ comment_count }}</span>
                                </a>
                </ul>
            </div>
        </div>
        <div class="dashboard-container-data">
            <div class="header">
                <h4 class="header-title">
                    Posts
                </h4>
            </div>
            <div class="dashboard-container-inner">
                {% if posts %}
                {% for post in posts %}
                    <div class="dashboard-data b-shadow mb-3">
                        <div class="data">
                            <div class="title">
                                <a href="{% url 'post-detail' post.slug %}">{{post.title|truncatechars:30}}</a>
                            </div>                    
                            <div class="draft">
                                <a href="{% url 'post-detail' post.slug %}">Published</a>
                            </div>
                            <div class="controls">
                                <input type="hidden" id="id-edit" value="{{post.slug}}">
                                <a class="post-delete" href="#">Delete</a>
                                <a class="edit" href="{% url 'edit-post' post.slug %}">Edit</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% else %}
                <h1>No Post</h1>
                {%  endif %}

                <input type="hidden" id="id-soc" data-url="{% url 'follow' request.user %}">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

core/templates/core/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark-custom bg-dark-custom">
    <div class="container">


    <a class="navbar-brand-custom" href="{% url 'index' %}">DEV</a>
    <form method="GET" action="{% url 'post-search' %}" class="form-inline my-2 my-lg-0 mr-auto">
      <div class="search-container">
        <input class="form-control mr-sm-2" type="search" placeholder="Search..." name="q" aria-label="Search" autocomplete="off">
      </div>
    </form>
    <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> -->

  
      {% if not request.user.is_authenticated %}
      <ul class="ml-auto navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link custom-nav login" href="{% url 'account_login' %}">Log in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link custom-nav create" href="{% url 'account_signup' %}">Create Account</a>
        </li>
      </ul>
      {% endif %}

      {% if request.user.is_authenticated %}
      <div class="dropdown right-side">
        <a class="nav-link custom-nav create" href="{% url 'add-post' %}">Write Post</a>
        <div class="d-author-profile nav-link dropdown " role="button" data-toggle="dropdown">

          <img src="{{request.user.profile_img.profile.url}}" alt="user profile" class="d-author-profile-img i-author-profile" >
        </div>
        <div class="dropdown-menu dropdown-menu-right search-toggle" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'profile' request.user %}">{{ request.user.get_full_name }}
            <div>
              <small>@{{ request.user.username }}</small>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'dashboard' %}">Dashboard</a>
          <a class="dropdown-item" href="{% url 'add-post' %}">Write Post</a>
          <a class="dropdown-item" href="{% url 'reading-list' %}">Reading List</a>
          <a class="dropdown-item" href="{% url 'profile-edit' %}">Settings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'account_confirm' %}">Logout</a>
        </div>
      </div>
      {% endif %}


</div>

  </nav>

core/templates/core/password_change.html
{% extends "core/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>

    <form method="POST" action="{% url 'account_change_password' %}" class="password_change">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="action">{% trans "Change Password" %}</button>
        <a href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
    </form>
{% endblock %}

core/templates/core/popup.html
<div class="popup center b-shadow">
    <div class="dismiss-btn">
      <button class="ml-auto dismiss-popup-btn">
        +
      </button>
    </div>
    <div class="row row-cols-2 following-followers-container">
        <!-- <div class="user-profile">
            <div class="icon">
                <img class="author-profile" src="{{request.user.profile_img.profile.url}}" alt="">
            </div>
            <div class="description">
              @cadientejomel
            </div>
           <form class="ml-auto" action="">
               <button>Following</button>
           </form>
        </div> -->
        
    </div>
  </div>

  <div class="center">

  </div>

core/templates/core/profile.html
{% extends 'core/base.html' %}
{% block content %}
<div class="container min-h pt-5">

<div class="user-profile-container mb-3">
    <div class="profile-img-container">
        <div class="profile-img-size">
            <img class="profile-img" src="{{ user.profile_img.profile.url }}" alt="">
        </div>
    </div>
    <div class="profile-info-container">
        <h3>{{user.username}}</h3>
        <p>{{user.profile_img.bio}}</p>
    </div>
    <div class="profile-more-container">
        <div class="m-auto profile-more">
            {% if user.profile_img.location %}
                <span class="p-2"><span class="mr-2"><i class="fas fa-map-marker-alt"></i></span>{{user.profile_img.location}}</span>
            {% endif %}
            <a href="mailto://{{user.email}}" class="p-2"><span class="mr-2" ><i class="fas fa-envelope"></i></span>{{user.email}}</a>
            <span class="p-2"><span class="mr-2"><i class="fas fa-birthday-cake"></i></span>Join on {{user.date_joined.date}}</span>
        </div>
    </div>

    {% if request.user.is_authenticated %}  
        {% if request.user != user %}
            {% if is_true %}
                <a class="file-btn edit-profile follow" href="{% url 'follow' user.username %}">
                Following
                </a>  
            {% else %}
                <a class="edit-profile custom-nav create follow" href="{% url 'follow' user.username %}">
                    Follow
                </a>  
            {% endif %}
            {% else %}
        <a class="edit-profile custom-nav create" href="{% url 'profile-edit' %}">Edit Profile</a>
        {% endif %}
    {% endif %}
</div>

<div class="body-layout">
    <div class="row">
        <div class="col-4">
            <div class="user-activities-container">

                <ul>
                    <li class="user-activities">
                        <span>
                            <i class="fas fa-user-friends"></i>
                        </span>
                        <form method="GET" action="{% url 'following' user.username %}" class="f-form">
                            {% csrf_token %}
                            <button href="#" class="open-popup-btn">{{ following_count}} Following</button>
                        </form>
                    </li>
                    <li class="user-activities">
                        <span>
                            <i class="fas fa-users"></i>
                        </span>
                        <form method="GET" action="{% url 'followers' user.username %}" class="f-form">
                            {% csrf_token %}
                            <button href="#" class="open-popup-btn">{{followers_count}} Follower</button>
                        </form>
                    </li>
                    <li class="user-activities"><span>
                        <i class="far fa-newspaper"></i>
                    </span>
                    {{post_count}} Post Published {{is_logged}}</li>
                    <li class="user-activities"><span>
                        <i class="far fa-comments"></i>
                    </span>
                    {{comment_count}} comments written</li>
                    <li class="user-activities"><span>
                        <i class="fas fa-book-reader"></i>
                    </span>
                    Reading List</li>
                    
                </ul>
            </div>
        </div>
        <div class="col-8">
            {% for list in user.post_set.all %}
            {% if not list.draft %}
            <div class="post-list-container mb-3 b-shadow">
                <div class="about-user-container mb-2">
                    <div class="prof-u">
                        <img class="author-profile" src="{{ list.author.profile_img.profile.url }}" alt="">
                        <div class="about-the-post">
                            <a class="post-about" href="{% url 'post-detail' list.slug %}">
                                <h5>{{ list.title }}</h5>
                            </a>
                        </div>
                    </div>
                </div>
                
                <div class="reactions">
                    <div class="mr-1">{{list.author}}</div>

                    <span class="divider-circle ml-1 mr-1"> • </span>
                    <div class="count-reactions mr-1 ml-1">
                        <i class="far fa-heart"></i> 
                        <span>{{ list.likes.count }} reactions</span>
                    </div>
                    <span class="divider-circle ml-1 mr-1"> • </span>
                    <span class="ml-1" id="date-c">{{ list.created }}</span>
                </div>
            </div>
            {% endif %}
                {% endfor %}

        </div>
    </div>
</div>
</div>
{% include 'core/popup.html' %}
</div>
<script>
    let dateContainer = document.querySelectorAll('#date-c')
    dateContainer.forEach(date => {
        let curr = date.textContent
        date.textContent = curr.split(',')[0]
    })

</script>
{% endblock content %}

core/templates/core/profile_edit.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container min-h pt-4">
    <div class="m-auto p-size ">

        <h1>Settings for <a href="{% url 'profile' request.user %}">
            @{{request.user}}
        </a></h1>
    </div>
    <div class="container p-size p-bg b-shadow">
        <h3>User</h3>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{u_form|crispy}}
            <label for="">Profile image</label>
            <div class="d-author-profile img-update-container">
                <img class="d-author-profile-img i-author-profile mr-3" src="{{ request.user.profile_img.profile.url }}" alt="user-profile">
                {{p_form|crispy}}
            </div>
        </div>
        <div class="p-size m-auto">

            <input class="ustom-nav create login-continue mt-3" type="submit" value="Update Profile">
        </div>
    </form>
</div>
{% endblock content %}

core/templates/core/reading_list.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="container min-h pt-4 ">
        {% if read_obj.post.all  %}
        <h3 class="mb-3">Reading List ({{read_obj.post.all.count}})</h3>
        {% for data in read_obj.post.all %}
        <div class="post-list-container mb-3 b-shadow">
            <div class="about-user-container mb-2">
                <div class="prof-u">
                   
                    <img class="author-profile" src="{{ data.author.profile_img.profile.url }}" alt="">
                    <div class="about-the-post">
                        <a class="post-about" href="{% url 'post-detail' data.slug %}">
                            <h5>{{ data.title }}</h5>
                            </a>
                       
                        
                       
                    </div>
                </div>
            </div>

            <div class="reactions">
                <div class="mr-1">{{data.author}}</div>
                <span class="divider-circle ml-1 mr-1"> • </span>
                <div class="count-reactions mr-1 ml-1">
                    <i class="far fa-heart"></i> 
                    <span>{{ data.likes.count }} reactions</span>    
                </div>
                <span class="divider-circle mr-1 ml-1"> • </span>
                <span class="ml-1" id="date-c">{{ data.created}}</span>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h3 class="mb-3">Reading List (0)</h3>
        <div class="read-box">
            <h3>Your reading list is empty...</h3>
        </div>
        {% endif %}
    </div>
    <script>
        let dateContainer = document.querySelectorAll('#date-c')
        dateContainer.forEach(date => {
            let curr = date.textContent
            date.textContent = curr.split(',')[0]
        })

    </script>
{% endblock content %}

core/templates/core/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Page</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{ forms.as_p }}
        <input type="submit" value="Register User">
    </form>
</body>
</html>